name: Fetch Logs

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download the metadata and upload the logs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download ${{ github.ref_name }}
          job=$(cat metadata.txt)
          gh run view --log --job=$job > logs.txt
          gh release upload ${{ github.ref_name }} logs.txt