name: Upload Logs

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Download the metadata and upload the logs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -ex
          gh release download ${{ github.ref_name }}
          run_id=$(cat metadata.txt)
          gh run view --log $run_id > logs.txt
          gh release upload ${{ github.ref_name }} logs.txt