name: Publish Python Package

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -ex
          while [ ! -f metadata.txt ]
          do 
            sleep 1
            gh release download
          end
          cat metadata.txt

      - name: Get Job ID from GH API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          job=$(cat metadata.txt)
          gh run view --log --job=$job