name: Fetch Logs

on:
  release:
    types: [published]

permissions:
  contents: read
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download the metadata and upload the logs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download ${{ github.ref_name }}
          job=$(cat metadata.txt)
          log=$(gh run view --log --job=$job)
          echo $log > logs.txt
          gh release upload ${{ github.ref_name }} logs.txt