name: Fetch Logs

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -ex
          while [ ! -f metadata.txt ]
          do 
            sleep 1
            gh release download ${{ github.ref_name }}
          end
          cat metadata.txt

      - name: Get Job ID from GH API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          job=$(cat metadata.txt)
          gh run view --log --job=$job > logs.txt
          gh release upload ${{ github.ref_name }} logs.txt